apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-deployment-test
spec:
  selector:
    matchLabels:
      app: music
  replicas: 2
  template: 
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: music
        image: yanivomc/spring-music:latest
        ports:
        - containerPort: 8080
       
---

kind: Service      
apiVersion: v1     
metadata:
  name: music-service
spec:
  selector:
    app: music 
  ports: 
  - name: myport 
    protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

