apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hare-stateful-test
spec:
  selector:
    matchLabels:
      app: hare
  replicas: 2
  template: 
    metadata:
      labels:
        app: hare
    spec:
      containers:
      - name: hare
        image: supergiantkir/animals:hare
        ports:
        - containerPort: 80
       
---

kind: Service      
apiVersion: v1     
metadata:
  name: animal-service
spec:
  selector:
    app: hare 
  ports: 
  - name: myport 
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
